pipeline {
    agent any
    // Global tools to be used by the pipeline
    tools { 
        maven 'maven-3.6.3' 
        jdk 'jdk8' 
    }
    parameters {
        string(name: "CODE_COVERAGE_QG", defaultValue: '0.5', description: 'Code coverage quality gate')
    }
    stages {
	    stage('Unit Tests') {
	        // Run Unit tests 
            steps{
                // sh 'mvn -f maths/pom.xml clean test'
                sh "mvn -f maths/pom.xml clean verify test -Dsuitename=unit_tests.xml -Dcoverage_quality_gate=${params.CODE_COVERAGE_QG}"
            }
        }	
        stage ('Artifactory configuration') {
            steps {
		        // specify Artifactory server
                rtServer (
                    id: "ARTIFACTORY_SERVER",
                    url: "http://artifactory:8081/artifactory",
		            credentialsId: 'admin.jfrog'
                )
		        // specify the repositories to be used for deploying the artifacts in the Artifactory
                rtMavenDeployer (
                    id: "MAVEN_DEPLOYER",
                    serverId: "ARTIFACTORY_SERVER",
                    releaseRepo: "jenkins-libs-release-local",
                    snapshotRepo: "jenkins-libs-snapshot-local"
                )
		        // defines the dependencies resolution details
                rtMavenResolver (
                    id: "MAVEN_RESOLVER",
                    serverId: "ARTIFACTORY_SERVER",
                    releaseRepo: "jenkins-libs-release",
                    snapshotRepo: "jenkins-libs-snapshot"
                )
            }
        }
        stage ('Build & Upload Artifact') {
	        // run Maven Build and upload the built artifact to Artifactory
            steps {
                rtMavenRun (
                    tool: "maven-3.6.3", // Tool name from Jenkins configuration
                    pom: 'maths/pom.xml',
                    goals: "clean install -Dcoverage_quality_gate=${params.CODE_COVERAGE_QG}",
                    deployerId: "MAVEN_DEPLOYER",
                    resolverId: "MAVEN_RESOLVER"
                )
            }
        }
        stage ('Publish build info') {
	        // Publish the build info in the Artifactory
            steps {
                rtPublishBuildInfo (
                    serverId: "ARTIFACTORY_SERVER"
                )
            }
        }
    }
}